# Generated by Django 5.2.6 on 2026-02-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_options_alter_cart_user_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.TextField(default=True),
        ),
    ]
