# Generated by Django 5.2.6 on 2026-02-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='description',
        ),
    ]
