# Generated by Django 5.2.6 on 2026-02-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('customer', 'Customer'), ('platform_admin', 'Platform Admin')], default='customer', max_length=20),
        ),
    ]
